GET https://velvetlettr.com/tf-backend/project/list-projects?courseId=3fd94fcf-e8f2-40dd-9182-b9ae48568c0b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZjMwN2QxLTRjZTQtNDBhNy1iMzQwLTgzMjRlM2Q4NWRjOCIsImlhdCI6MTczMTQ4OTA4MCwiZXhwIjoxNzMxNDkyNjgwfQ.uT5rJwMCuoHlnOnAaEM8j4cFldRxuE72Ze4toeA_9dk
