GET https://velvetlettr.com/tf-backend/project/received-invitations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzNzViOTYxLTVkZTQtNDY3NS1iZTA5LTQyOWM3MGE3MTQ2NCIsImlhdCI6MTczMTYxNzk4MCwiZXhwIjoxNzMxNjIxNTgwfQ.JxH1WsNumvrBTb_TwQxhAf6lJCFT9uw6WxjXhMIEkHs