GET https://velvetlettr.com/tf-backend/project/project-applicants?projectId=9d281d42-823f-428f-9244-5f326735cd78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YThkNmNmLTk4ZGQtNGY3Mi1hYTE3LWMyMGM3NDNmYjNjNCIsImlhdCI6MTczMTA2MDIzOSwiZXhwIjoxNzMxMDYzODM5fQ.-9aAlWMjAwQsuMqjslimAg6dvMIxMU-u1hQt8ua4R38