GET https://velvetlettr.com/tf-backend/project/projects-applications/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YThkNmNmLTk4ZGQtNGY3Mi1hYTE3LWMyMGM3NDNmYjNjNCIsImlhdCI6MTczMTA2MDAwMywiZXhwIjoxNzMxMDYzNjAzfQ.wiki7rtrOXAFHtQoJNLFTNjliryrmeKH7o6wJCGA0h4

