POST https://velvetlettr.com/tf-backend//course/join-course/1a732828-39e4-4901-bda1-bcaf1e4fe1b0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxNWFjYWY3LWZhYmQtNDZlMC04MTUxLWI1YTZiNmZmMzkwNiIsImlhdCI6MTczMDk2OTAwMSwiZXhwIjoxNzMwOTcyNjAxfQ.uWakF6_InNm4yw3qbvkH_DhtQkwTYgS7oRe5Q45DO_I
